# Data
Yelp open dataset is used for the project (https://www.yelp.com/dataset).
The data is pretty clean.

The purpose of the wrangling is to get the reviews of Toronto restaurant from the dataset.

# Related Files
review.json

In [3]:
import pandas as pd
reviews = pd.read_json('review_sample.json', lines=True)
reviews.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,ujmEBvifdJM6h6RLv4wQIg,0,2013-05-07 04:34:36,1,Q1sbwvVQXV2734tPgoKj4Q,1,Total bill for this horrible service? Over $8G...,6,hG7b0MtEbXx5QzbzE6C_VA
1,NZnhc2sEQy3RmzKTZnqtwQ,0,2017-01-14 21:30:33,0,GJXCdrto3ASJOqKeVWPi6Q,5,I *adore* Travis at the Hard Rock's new Kelly ...,0,yXQM5uF2jS6es16SJzNHfg
2,WTqjgwHlXbSFevF32_DJVw,0,2016-11-09 20:09:03,0,2TzJjDVDEuAW6MR5Vuc1ug,5,I have to say that this office really has it t...,3,n6-Gk65cPZL6Uz8qRm3NYw
3,ikCg8xy5JIg_NGPx-MSIDA,0,2018-01-09 20:56:38,0,yi0R0Ugj_xUx_Nek0-_Qig,5,Went in for a lunch. Steak sandwich was delici...,0,dacAIZ6fTM6mqwW5uxkskg
4,b1b1eb3uo-w561D0ZfCEiQ,0,2018-01-30 23:07:38,0,11a8sVPMUFtaC7_ABRkmtw,1,Today was my second out of three sessions I ha...,7,ssoyf2_x0EQMed6fgHeMyQ

business.json

In [4]:
business = pd.read_json('business.json', lines=True)
business.head()

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,postal_code,review_count,stars,state
0,2818 E Camino Acequia Drive,{'GoodForKids': 'False'},1SWheh84yJXfytovILXOAQ,"Golf, Active Life",Phoenix,None,0,33.522143,-112.018481,Arizona Biltmore Golf Club,85016,5,3.0,AZ
1,30 Eglinton Avenue W,"{'RestaurantsReservations': 'True', 'GoodForMe...",QXAEGFB4oINsVuTFxEYKFQ,"Specialty Food, Restaurants, Dim Sum, Imported...",Mississauga,"{'Monday': '9:0-0:0', 'Tuesday': '9:0-0:0', 'W...",1,43.605499,-79.652289,Emerald Chinese Restaurant,L5R 3E7,128,2.5,ON
2,"10110 Johnston Rd, Ste 15","{'GoodForKids': 'True', 'NoiseLevel': 'u'avera...",gnKjwL_1w79qoiV3IC_xQQ,"Sushi Bars, Restaurants, Japanese",Charlotte,"{'Monday': '17:30-21:30', 'Wednesday': '17:30-...",1,35.092564,-80.859132,Musashi Japanese Restaurant,28210,170,4.0,NC
3,"15655 W Roosevelt St, Ste 237",None,xvX2CttrVhyG2z1dFg_0xw,"Insurance, Financial Services",Goodyear,"{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ...",1,33.455613,-112.395596,Farmers Insurance - Paul Lorenz,85338,3,5.0,AZ
4,"4209 Stuart Andrew Blvd, Ste F","{'BusinessAcceptsBitcoin': 'False', 'ByAppoint...",HhyxOkGAM07SRYtlQ4wMFQ,"Plumbing, Shopping, Local Services, Home Servi...",Charlotte,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,35.190012,-80.887223,Queen City Plumbing,28217,4,4.0,NC

# Steps
1. Get Toronto restaurant from business.json by categories and city.

In [6]:
toronto_business = business[business.city == 'Toronto']
toronto_restaurant = toronto_business[toronto_business['categories'].str.contains('Restaurants', na=True)]
toronto_restaurant.head()

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,postal_code,review_count,stars,state
29,1170 Queen Street W,"{'WiFi': 'u'no'', 'BikeParking': 'True', 'Rest...",NDuUMJfrWk52RA-H-OtrpA,"Juice Bars & Smoothies, Food, Restaurants, Fas...",Toronto,"{'Monday': '8:0-21:0', 'Tuesday': '8:0-21:0', ...",1,43.642889,-79.425429,Bolt Fresh Bar,M6J 1J5,57,3.0,ON
32,1051 Bloor Street W,"{'BusinessParking': '{'garage': False, 'street...",SP_YXIEwkFPPl_9anCYmpQ,"Restaurants, Nightlife, Breakfast & Brunch, Ve...",Toronto,"{'Tuesday': '9:0-18:0', 'Wednesday': '9:0-18:0...",0,43.660494,-79.432099,The Steady Cafe & Bar,M6H 1M4,29,3.5,ON
50,582 College Street,"{'Alcohol': 'u'full_bar'', 'Caters': 'False', ...",mlHC2XcU9Bows6cnYEmRgg,"Restaurants, Breakfast & Brunch, Bars, Modern ...",Toronto,"{'Thursday': '18:0-2:0', 'Friday': '18:0-2:0',...",0,43.655420,-79.413352,Mad Crush Wine Bar,M6G 1B3,9,4.0,ON
83,619 Mount Pleasant Road,"{'RestaurantsPriceRange2': '2', 'HasTV': 'Fals...",RFbMVekR8lU9tPJ8sWrwHg,"Italian, Restaurants",Toronto,None,1,43.704229,-79.388230,Tavolino,M4S 2M5,18,4.0,ON
96,1614 Queen Street E,"{'RestaurantsGoodForGroups': 'True', 'Restaura...",NPHZkn1e-tSJAbo8Zm9rYw,"Tex-Mex, Mexican, Restaurants",Toronto,"{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",1,43.666181,-79.316468,Burrito Bandidos,M4L 1G4,43,3.5,ON

2. Read reviews from review.json by chunk and merge it with Toronto restaurants.

In [7]:
%%time

reader = pd.read_json('review.json', chunksize=100000, lines=True)
toronto_restaurant_review = pd.DataFrame()
for chunk in reader:
    toronto_restaurant_review = toronto_restaurant_review.append(chunk.merge(toronto_restaurant, on='business_id'))

CPU times: user 3min 3s, sys: 19.8 s, total: 3min 22s
Wall time: 2min 32s

In [9]:
toronto_restaurant_review.head()

,business_id,cool,date,funny,review_id,stars_x,text,useful,user_id,address,...,city,hours,is_open,latitude,longitude,name,postal_code,review_count,stars_y,state
0,AakkkTuGZA2KBodKi2_u8A,0,2012-07-16 00:37:14,1,JVcjMhlavKKn3UIt9p9OXA,1,I cannot believe how things have changed in 3 ...,1,TpyOT5E16YASd7EWjLQlrw,1603 Dundas Street W,...,Toronto,"{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",1,43.649674,-79.435116,Pho Phuong,M6K 1T9,55,3.5,ON
1,AakkkTuGZA2KBodKi2_u8A,0,2014-02-24 01:45:02,0,vKhtzhPUz9RJbllyvHm3qA,3,"Pretty good, food,, about the same as other vi...",0,G-9ujgKmc1J2k7HSqXszsw,1603 Dundas Street W,...,Toronto,"{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",1,43.649674,-79.435116,Pho Phuong,M6K 1T9,55,3.5,ON
2,AakkkTuGZA2KBodKi2_u8A,0,2016-02-12 00:25:23,0,Je6AF9sTKwXwOVw2YHR1dg,5,I've been going to this place since it opened ...,0,NA4sslQXta6U263fqzwKiw,1603 Dundas Street W,...,Toronto,"{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",1,43.649674,-79.435116,Pho Phuong,M6K 1T9,55,3.5,ON
3,AakkkTuGZA2KBodKi2_u8A,0,2013-05-07 06:03:17,0,b_xVF8U5Vqljz58OUEjqgA,4,One of the best Vietnamese places I`ve tried i...,1,1fNQRju9gmoCEvbPQBSo7w,1603 Dundas Street W,...,Toronto,"{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",1,43.649674,-79.435116,Pho Phuong,M6K 1T9,55,3.5,ON
4,AakkkTuGZA2KBodKi2_u8A,0,2011-11-30 16:46:24,0,vFPpG1xDBSWcvy_165fxKg,3,"This place is just ok. Nice atmosphere, big op...",0,fYJGKhZK2FZckYWDMdCooA,1603 Dundas Street W,...,Toronto,"{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",1,43.649674,-79.435116,Pho Phuong,M6K 1T9,55,3.5,ON

3. Reset business_id and review_id as indexes.

In [10]:
toronto_restaurant_review = toronto_restaurant_review.set_index(['business_id', 'review_id'])
toronto_restaurant_review.head()

                                               cool                date  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA     0 2012-07-16 00:37:14
                       vKhtzhPUz9RJbllyvHm3qA     0 2014-02-24 01:45:02
                       Je6AF9sTKwXwOVw2YHR1dg     0 2016-02-12 00:25:23
                       b_xVF8U5Vqljz58OUEjqgA     0 2013-05-07 06:03:17
                       vFPpG1xDBSWcvy_165fxKg     0 2011-11-30 16:46:24

                                               funny  stars_x  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA      1        1
                       vKhtzhPUz9RJbllyvHm3qA      0        3
                       Je6AF9sTKwXwOVw2YHR1dg      0        5
                       b_xVF8U5Vqljz58OUEjqgA      0        4
                       vFPpG1xDBSWcvy_165fxKg      0        3

                                                                                            text  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  I cannot believe how things have changed in 3 ...
                       vKhtzhPUz9RJbllyvHm3qA  Pretty good, food,, about the same as other vi...
                       Je6AF9sTKwXwOVw2YHR1dg  I've been going to this place since it opened ...
                       b_xVF8U5Vqljz58OUEjqgA  One of the best Vietnamese places I`ve tried i...
                       vFPpG1xDBSWcvy_165fxKg  This place is just ok. Nice atmosphere, big op...

                                               useful                 user_id  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA       1  TpyOT5E16YASd7EWjLQlrw
                       vKhtzhPUz9RJbllyvHm3qA       0  G-9ujgKmc1J2k7HSqXszsw
                       Je6AF9sTKwXwOVw2YHR1dg       0  NA4sslQXta6U263fqzwKiw
                       b_xVF8U5Vqljz58OUEjqgA       1  1fNQRju9gmoCEvbPQBSo7w
                       vFPpG1xDBSWcvy_165fxKg       0  fYJGKhZK2FZckYWDMdCooA

                                                            address  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  1603 Dundas Street W
                       vKhtzhPUz9RJbllyvHm3qA  1603 Dundas Street W
                       Je6AF9sTKwXwOVw2YHR1dg  1603 Dundas Street W
                       b_xVF8U5Vqljz58OUEjqgA  1603 Dundas Street W
                       vFPpG1xDBSWcvy_165fxKg  1603 Dundas Street W

                                                                                      attributes  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  {'Caters': 'False', 'OutdoorSeating': 'False',...
                       vKhtzhPUz9RJbllyvHm3qA  {'Caters': 'False', 'OutdoorSeating': 'False',...
                       Je6AF9sTKwXwOVw2YHR1dg  {'Caters': 'False', 'OutdoorSeating': 'False',...
                       b_xVF8U5Vqljz58OUEjqgA  {'Caters': 'False', 'OutdoorSeating': 'False',...
                       vFPpG1xDBSWcvy_165fxKg  {'Caters': 'False', 'OutdoorSeating': 'False',...

                                                                          categories  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  Asian Fusion, Restaurants, Vietnamese
                       vKhtzhPUz9RJbllyvHm3qA  Asian Fusion, Restaurants, Vietnamese
                       Je6AF9sTKwXwOVw2YHR1dg  Asian Fusion, Restaurants, Vietnamese
                       b_xVF8U5Vqljz58OUEjqgA  Asian Fusion, Restaurants, Vietnamese
                       vFPpG1xDBSWcvy_165fxKg  Asian Fusion, Restaurants, Vietnamese

                                                  city  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  Toronto
                       vKhtzhPUz9RJbllyvHm3qA  Toronto
                       Je6AF9sTKwXwOVw2YHR1dg  Toronto
                       b_xVF8U5Vqljz58OUEjqgA  Toronto
                       vFPpG1xDBSWcvy_165fxKg  Toronto

                                                                                           hours  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...
                       vKhtzhPUz9RJbllyvHm3qA  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...
                       Je6AF9sTKwXwOVw2YHR1dg  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...
                       b_xVF8U5Vqljz58OUEjqgA  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...
                       vFPpG1xDBSWcvy_165fxKg  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...

                                               is_open   latitude  longitude  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA        1  43.649674 -79.435116
                       vKhtzhPUz9RJbllyvHm3qA        1  43.649674 -79.435116
                       Je6AF9sTKwXwOVw2YHR1dg        1  43.649674 -79.435116
                       b_xVF8U5Vqljz58OUEjqgA        1  43.649674 -79.435116
                       vFPpG1xDBSWcvy_165fxKg        1  43.649674 -79.435116

                                                     name postal_code  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  Pho Phuong     M6K 1T9
                       vKhtzhPUz9RJbllyvHm3qA  Pho Phuong     M6K 1T9
                       Je6AF9sTKwXwOVw2YHR1dg  Pho Phuong     M6K 1T9
                       b_xVF8U5Vqljz58OUEjqgA  Pho Phuong     M6K 1T9
                       vFPpG1xDBSWcvy_165fxKg  Pho Phuong     M6K 1T9

                                               review_count  stars_y state
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA            55      3.5    ON
                       vKhtzhPUz9RJbllyvHm3qA            55      3.5    ON
                       Je6AF9sTKwXwOVw2YHR1dg            55      3.5    ON
                       b_xVF8U5Vqljz58OUEjqgA            55      3.5    ON
                       vFPpG1xDBSWcvy_165fxKg            55      3.5    ON

4. Rename columns

In [11]:
toronto_restaurant_review = toronto_restaurant_review.rename(
    columns={'stars_x': 'stars_business', 'stars_y': 'stars_review'})
toronto_restaurant_review.head()

                                               cool                date  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA     0 2012-07-16 00:37:14
                       vKhtzhPUz9RJbllyvHm3qA     0 2014-02-24 01:45:02
                       Je6AF9sTKwXwOVw2YHR1dg     0 2016-02-12 00:25:23
                       b_xVF8U5Vqljz58OUEjqgA     0 2013-05-07 06:03:17
                       vFPpG1xDBSWcvy_165fxKg     0 2011-11-30 16:46:24

                                               funny  stars_business  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA      1               1
                       vKhtzhPUz9RJbllyvHm3qA      0               3
                       Je6AF9sTKwXwOVw2YHR1dg      0               5
                       b_xVF8U5Vqljz58OUEjqgA      0               4
                       vFPpG1xDBSWcvy_165fxKg      0               3

                                                                                            text  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  I cannot believe how things have changed in 3 ...
                       vKhtzhPUz9RJbllyvHm3qA  Pretty good, food,, about the same as other vi...
                       Je6AF9sTKwXwOVw2YHR1dg  I've been going to this place since it opened ...
                       b_xVF8U5Vqljz58OUEjqgA  One of the best Vietnamese places I`ve tried i...
                       vFPpG1xDBSWcvy_165fxKg  This place is just ok. Nice atmosphere, big op...

                                               useful                 user_id  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA       1  TpyOT5E16YASd7EWjLQlrw
                       vKhtzhPUz9RJbllyvHm3qA       0  G-9ujgKmc1J2k7HSqXszsw
                       Je6AF9sTKwXwOVw2YHR1dg       0  NA4sslQXta6U263fqzwKiw
                       b_xVF8U5Vqljz58OUEjqgA       1  1fNQRju9gmoCEvbPQBSo7w
                       vFPpG1xDBSWcvy_165fxKg       0  fYJGKhZK2FZckYWDMdCooA

                                                            address  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  1603 Dundas Street W
                       vKhtzhPUz9RJbllyvHm3qA  1603 Dundas Street W
                       Je6AF9sTKwXwOVw2YHR1dg  1603 Dundas Street W
                       b_xVF8U5Vqljz58OUEjqgA  1603 Dundas Street W
                       vFPpG1xDBSWcvy_165fxKg  1603 Dundas Street W

                                                                                      attributes  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  {'Caters': 'False', 'OutdoorSeating': 'False',...
                       vKhtzhPUz9RJbllyvHm3qA  {'Caters': 'False', 'OutdoorSeating': 'False',...
                       Je6AF9sTKwXwOVw2YHR1dg  {'Caters': 'False', 'OutdoorSeating': 'False',...
                       b_xVF8U5Vqljz58OUEjqgA  {'Caters': 'False', 'OutdoorSeating': 'False',...
                       vFPpG1xDBSWcvy_165fxKg  {'Caters': 'False', 'OutdoorSeating': 'False',...

                                                                          categories  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  Asian Fusion, Restaurants, Vietnamese
                       vKhtzhPUz9RJbllyvHm3qA  Asian Fusion, Restaurants, Vietnamese
                       Je6AF9sTKwXwOVw2YHR1dg  Asian Fusion, Restaurants, Vietnamese
                       b_xVF8U5Vqljz58OUEjqgA  Asian Fusion, Restaurants, Vietnamese
                       vFPpG1xDBSWcvy_165fxKg  Asian Fusion, Restaurants, Vietnamese

                                                  city  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  Toronto
                       vKhtzhPUz9RJbllyvHm3qA  Toronto
                       Je6AF9sTKwXwOVw2YHR1dg  Toronto
                       b_xVF8U5Vqljz58OUEjqgA  Toronto
                       vFPpG1xDBSWcvy_165fxKg  Toronto

                                                                                           hours  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...
                       vKhtzhPUz9RJbllyvHm3qA  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...
                       Je6AF9sTKwXwOVw2YHR1dg  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...
                       b_xVF8U5Vqljz58OUEjqgA  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...
                       vFPpG1xDBSWcvy_165fxKg  {'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...

                                               is_open   latitude  longitude  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA        1  43.649674 -79.435116
                       vKhtzhPUz9RJbllyvHm3qA        1  43.649674 -79.435116
                       Je6AF9sTKwXwOVw2YHR1dg        1  43.649674 -79.435116
                       b_xVF8U5Vqljz58OUEjqgA        1  43.649674 -79.435116
                       vFPpG1xDBSWcvy_165fxKg        1  43.649674 -79.435116

                                                     name postal_code  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA  Pho Phuong     M6K 1T9
                       vKhtzhPUz9RJbllyvHm3qA  Pho Phuong     M6K 1T9
                       Je6AF9sTKwXwOVw2YHR1dg  Pho Phuong     M6K 1T9
                       b_xVF8U5Vqljz58OUEjqgA  Pho Phuong     M6K 1T9
                       vFPpG1xDBSWcvy_165fxKg  Pho Phuong     M6K 1T9

                                               review_count  stars_review  \
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA            55           3.5
                       vKhtzhPUz9RJbllyvHm3qA            55           3.5
                       Je6AF9sTKwXwOVw2YHR1dg            55           3.5
                       b_xVF8U5Vqljz58OUEjqgA            55           3.5
                       vFPpG1xDBSWcvy_165fxKg            55           3.5

                                              state
business_id            review_id
AakkkTuGZA2KBodKi2_u8A JVcjMhlavKKn3UIt9p9OXA    ON
                       vKhtzhPUz9RJbllyvHm3qA    ON
                       Je6AF9sTKwXwOVw2YHR1dg    ON
                       b_xVF8U5Vqljz58OUEjqgA    ON
                       vFPpG1xDBSWcvy_165fxKg    ON